import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react/cjs/react.production.min'
import styles from '../styles/Home.module.css'


async function getServerSideProps(res, data) {
  res = await fetch(`http://localhost:3000/api/hello`)
  data = await res.json()
  if (!res.ok) {
    // If there is a server error, you might want to
    // throw an error instead of returning so that the cache is not updated
    // until the next successful request.
    throw new Error(`Failed to fetch posts, received status ${res.status}`)
  }
  console.log("DATA FROM SERVER===>>>", data)
}

const _alertMe = () => {
  alert("RED ALERT")
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to VirtuLunch
        </h1>

        <p className={styles.description}>
          Choose your random lunch mate :)
        </p>

        <div className={styles.grid}>
          <div>Here is the employeers</div>
          <div><button onClick={getServerSideProps}>Get Data</button></div>
        </div>

        <div className={styles.grid}>

          <div>{ }</div>
        </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
